sudo: false
language: node_js
node_js:
- '6'
- '8'
install:
- yarn
script:
- yarn test
after_success:
- npx codecov
deploy:
  provider: npm
  email: winkeyme@163.com
  api_key:
    secure: VJZTeSB9vAJh4jOu0qJqSYRHeuabel/gNIqAf9RnQMvTFJFd7IjqCKFUvo8hwYEQC238aQ7Imuxp4PwEV1lLupKhDAfKiwsUGsJPvTsPs4bxK1cYKeo2gVXcXH4eo+ROaxxpRQRXCZ8h7WXpOAazqV1lWlCBSvaDdWRkGDCu2wBEguh9E9ZjJ/NaDAUZwVry1PtfiVdXRJLyQphwC+bLL1MJyP2A26/mbhIhTrfbApjbbWh1C6jgj3u5rAo8VVPUt7j+nFQ5xK1d6Dkbt8v6XeEDut/3cSdg2dnqru37vp5OR4FsCVXNZZmLket5Kp5v/z0hH7P3ztJd+SnidVFn3VW9cOL5+mFXIBGNFPN2tLJ7k5TwIR9sQ07zY0Qu9Y8FdboJQnDeWVxntPBN71hySRyU59OqVgdpjOV054JcfJIGsp7344EwdDAXxrCnrP0ekpSWdQ1q8PSp8Ie2Jb3odyWXxJjiyRn92p5VgpRSdtUNuIisZxJZcmz0z5X8MSHQa97YVSJUKv86WXZO1oWll8tjngIgQkPtOy8TovZlKutjhA98OCCcO0umRPLp1ctkuY3T65rGDKgnDh+mW0Tvpp+Umszw/RjPrYEsut5C1p6HZWzsn/I0DukA5Q5h85CeIEU6PUwry4JOLQge2odCkpHoS1R1975vQ/slJXoGCqE=
  on:
    tags: true
    node: '6'
  skip_cleanup: true
